baseurl = "http://github.com/hands-on-scala/hands-on-scala.github.io/"
languageCode = "en-us"
title = "Hands-on Scala Blog"
canonifyurls = true
theme = "hugo-base16-theme"
publishdir = "/home/adri/hands-on-scala.github.io/"
